messages:
  hello: Hello world from Hemant!
server:
    applicationConnectors:
      - type: https
        port: 8443
        keyStoreType: PKCS12
        keyStorePath: .\src\main\resources\certificates\keyStore.p12
        keyStorePassword: password
        keyManagerPassword: password
        trustStoreType: PKCS12
        trustStorePath: .\src\main\resources\certificates\trustStore.p12
        trustStorePassword: password
        certAlias: bisserver
        keyManagerPassword: password
        needClientAuth: true
        wantClientAuth: true
logging:
  appenders:
    - type: console
      threshold: WARN
      target: stderr